[package]
name = "bare_metal"
version = "0.1.0"
authors = ["matlapo <mathieu.lapointe3@mail.mcgill.ca>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.6.0"
volatile = "0.2.3"
